# database container deployment
kind: pipeline
name: BD

steps:  
  - name: deploy-container-mysql
    image: mysql:latest
    environment:
        IMAGENAME: mysql:latest
        CONTAINERNAME: mysql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        environment:
          MYSQL_ROOT_PASSWORD:
            from_secret: P@s$w0rd123
          MYSQL_DATABASE:
            from_secret: BDBOB
          MYSQL_USER:
            from_secret: bob
          MYSQL_PASSWORD:
            from_secret: P@s$w0rd123