# database container deployment
kind: pipeline
name: BD

steps:  
  - name: deploy-container-mysql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: mysql-cluster:7.5
        CONTAINERNAME: mysql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_ROOT_PASSWORD:
          from_secret: P@s$w0rd123
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_DATABASE:
          from_secret: BDBOB
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_USER:
          from_secret: bob
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_PASSWORD:
          from_secret: P@s$w0rd12