# database container deployment
kind: pipeline
name: Dockers_Builder

steps:  
  - name: deploy-mysql-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: mysql:8.0
      CONTAINERNAME: mysql
      COMMAND: create
      # OVERWRITE: false
      PRIVATE: true
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_ROOT_PASSWORD:          
        from_secret: R00tPassw0rd*        
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_DATABASE:          
        from_secret: DataBob       
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_USER:          
        from_secret: bob       
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_PASSWORD:          
        from_secret: B0bPassw0rd*


  - name: deploy-container
    image: hub.docker.com/r/reactnativecommunity/react-native-android:latest
    environment:
      IMAGENAME: react-native-android:latest
      CONTAINERNAME: container_react
      COMMAND: create
      PRIVATE: true
      OVERWRITE: true