# database container deployment
kind: pipeline
name: BD

steps:  
  - name: deploy-container-mysql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: mysql:10
        CONTAINERNAME: mysql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_ROOT_PASSWORD:
          from_secret: P@s$w0rd123
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_DATABASE:
          from_secret: BDBOB
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_USER:
          from_secret: bob
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_PASSWORD:
          from_secret: P@s$w0rd123
    commands:
      - GRANT ALL PRIVILEGES ON *.* TO 'CODEFIRST_CLIENTDRONE_ENV_MARIADB_USER'@'localhost' IDENTIFIED BY 'CODEFIRST_CLIENTDRONE_ENV_MARIADB_PASSWORD';
      