kind: pipeline
name: Dockers_Builder


# Creation of the DB docker
steps:  
  # database container deployment
  - name: deploy-container-mysql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: mysql:8.0
        CONTAINERNAME: mysql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: false
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_ROOT_PASSWORD:
          from_secret: MYSQL_ROOT_PASSWORD
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_DATABASE:
          from_secret: MYSQL_DATABASE
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_USER:
          from_secret: MYSQL_USER
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_PASSWORD:
          from_secret: MYSQL_PASSWORD