# database container deployment
kind: pipeline
name: BD

steps:  
  - name: deploy-mysql-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: mysql:8.0
      CONTAINERNAME: mysql
      COMMAND: create
      # OVERWRITE: false
      PRIVATE: true
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_ROOT_PASSWORD:          
        from_secret: db_root_password        
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_DATABASE:          
        from_secret: db_database        
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_USER:          
        from_secret: db_user        
      CODEFIRST_CLIENTDRONE_ENV_MYSQL_PASSWORD:          
        from_secret: db_password